const ExampleData = [
	'Mexican Black Bean Soup',
	'Eggplant Babakanoosh',
	'Bathingan bel Khal Wel thome',
	'Lebanese Tabbouleh',
	'BabaGhanooj',
	'Falfafel',
	'Pita Bread',
	'Kebab Koubane',
	'Moroccan Yogurt Dip',
	'Persian Cutlet',
	'Omlet',
	'Hommas Balil',
	'Marghareta Pizza',
	'Cannoli',
	'North Italian Cannoli',
	'Iced Florentine',
	'Artichoke Hummus',
	'Baked White Bean Dip',
	'Black Bean Dip',
	'Blood Orange and Green Olive Salad',
	'Bruschetta Three Ways',
	'Chili Garlic Corn Chips',
	'Chilled Ginger Cantaloupe Soup',
	'Chipotle Bacon Deviled Eggs',
	'Coconut Shrimp Poppers',
	'Creamy Blue Cheese Dip',
	'Deviled Eggs',
	'Herbed Cheddar Parmesan Crisps',
	"Kettle Corn",
	'Maple-Rosemary Glazed Walnuts',
	'Nando’s Honey Garlic Wings',
	'Pickled Serrano Chiles',
	'Potato Taquitos',
	'Pumpkin Spice Cream Cheese Spread',
	'Roasted Red Pepper Hummus',
	'Rosemary Garlic Sweet Potato Fries',
	'Slow-Roasted Cherry Tomatoes',
	'Smoked Tuna Dip',
	'Spicy Pickled Garlic',
	'Spinach and Feta Turnovers',
	'Sun-dried Tomato Hummus',
	'Spice Roasted Almonds',
	'Tzatziki Sauce (cucumber yogurt dip)',
	'Whole Wheat Pita Chips'
]
export default ExampleData